version: 2
updates:
  - package-ecosystem: "npm" # Check for npm dependencies
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
          - "*" # Group all updates into one PR to avoid noise
